//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Idf.rc
//
#define IDR_MAINFRAME                   2
#define ID_AYUDA                        3
#define IDR_PROYTYPE                    3
#define IDR_PROYTYPE_SRVR_IP            4
#define IDR_PROYTYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         101
#define IDD_MENSAJE                     101
#define IDR_MENU_BLOQUE_FUNC_DCHO       101
#define IDD_CONFIRM                     102
#define ID_OBJECT_POPUP_MENU            102
#define IDD_BLOQUE                      103
#define IDS_PRIVATE_CF_DESCR            103
#define IDC_TEXTOMEN                    105
#define IDD_TABLADISENO                 107
#define IDB_BLQFUNC_DLL                 109
#define IDD_LOGDIAG                     110
#define IDD_PROP_REJILLA                111
#define IDR_MENU_CONSOLA                113
#define IDR_PROYTYPE_SRVR_EMB           114
#define IDD_PROP_BLOQUE                 114
#define IDR_PROY_DISENO                 115
#define IDD_CANCEL_AUTO                 116
#define IDR_MENU_CONEC_DCHO             116
#define IDD_PROP_BLOQUE_DIAG            117
#define IDD_PROP_BLOQUE_DLL             118
#define IDD_PROP_DIAG                   119
#define IDD_PROP_CONECT                 120
#define IDC_ETIQ                        122
#define IDD_NUEVOTXT                    129
#define IDB_RECTANG                     130
#define IDB_ROMBO                       131
#define IDB_CIRCULO                     132
#define IDB_BLQFUNC_DIAG                133
#define IDD_MULTIDIAG                   133
#define IDB_BLQRETRO                    134
#define IDB_CONFUNC                     135
#define IDC_LISTA_CON                   135
#define IDD_OPERAC_BLOQUE               135
#define IDB_CONRETRO                    136
#define IDD_OPERAC_BRETRO               136
#define IDC_AYUDA                       136
#define IDD_MENSAJE_EXT                 137
#define IDC_ESTADOUSUARIO               137
#define IDC_MACRO                       137
#define IDD_BLOQUEDIS                   138
#define IDD_NUDOCON                     139
#define IDC_ETIQUETA                    140
#define IDC_ACTIVO_ENTRADA              142
#define IDC_ACTIVO_SALIDA               143
#define IDD_PROP_BLOQUE_INFORM          145
#define IDD_PROP_DIAG_INFORM            146
#define IDD_PROP_CONECT_INFORM          148
#define IDD_ANALISIS_DLL                150
#define IDD_ANALISIS_CLASE              151
#define IDD_PROP_DIAG_COMPONENTES       153
#define IDI_BLOQUES                     154
#define IDD_PROP_BLOQUE_CONECTORES      154
#define IDI_CONECTORES                  155
#define IDI_CONECTOR                    156
#define IDC_ESTADOINTERNO               157
#define IDI_BLOQUE                      157
#define IDC_BLOQUE_FIN                  158
#define IDC_ORDEN_BLOQUE                158
#define IDD_PROP_CLASES_CON_DLL         158
#define IDC_TIPO_DIBUJO                 159
#define IDR_MENU_CLASEDLL_POPUP         159
#define IDD_PROP_CLASES_SIN_DLL         159
#define IDC_DIAG_HIJO                   160
#define IDR_MENU_COMPONENTE_PROP_POPUP  160
#define IDD_PROP_CONECT_INICIO_DLL      160
#define IDD_PROP_CONECT_FIN_DLL         161
#define IDR_MENU_BLOQUE_DIS_DCHO        161
#define IDC_BLOQUE_INICIO               162
#define IDC_HIJOTIPOFICH                164
#define IDC_TIPO_BLOQUE                 166
#define IDC_SALIDA_AUTO                 169
#define IDC_MAXITER_AUTO                170
#define IDC_PROP_FIN                    171
#define IDC_ID                          171
#define IDC_PROP_INICIO                 172
#define IDC_PROP_DIAGHIJO               173
#define IDC_CAMBIA_HIJO                 175
#define IDC_FICHBIN                     176
#define IDC_DLLBLOQUE                   178
#define IDC_CAMBIA_DLL                  179
#define IDC_USADLLDIAG                  180
#define IDC_GENERAR_CODIGO              180
#define IDC_PROP_USUARIO                181
#define IDC_PROPBLOQ_FIN                182
#define IDC_TITULO                      184
#define IDC_FICHLDD                     185
#define IDC_CAMBIA_LDD                  186
#define IDC_USADLL                      187
#define IDC_DLLDIAG                     188
#define IDC_CAMBIA_DLLDIAG              189
#define IDC_TEXTO_AYUDA                 192
#define IDC_FICH_HIJO                   193
#define IDC_BLOQUE_INICIAL              194
#define IDC_PROPBLOQ_INI                196
#define IDC_TEXTO                       198
#define IDC_CONECTOR_ETIQ               198
#define IDC_FECHA                       199
#define IDC_VENT_HIJO                   200
#define IDC_DIAG_PADRE                  205
#define IDC_PROP_DIAGPADRE              206
#define IDC_VISIBLE                     207
#define IDC_PROP_BLOQUEDIAG             207
#define IDC_RETROANOTA                  213
#define IDC_ACEPTAR_DATOS               214
#define IDC_DEVOLVER_DATOS              215
#define IDC_RECIBIR_RETROANO            216
#define IDC_ENVIAR_RETROANO             217
#define IDC_ACCION                      218
#define IDC_OPERACIONES                 218
#define IDP_CLIPBOARD_CUT_FAILED        0x201
#define IDP_CLIPBOARD_COPY_FAILED       0x202
#define IDP_GET_FROM_CLIPBOARD_FAILED   0x203
#define IDP_SAVEINCOMPLETE              0x205
#define IDC_INS_BLQFUNC_DIAG            1005
#define IDC_INS_BLQ_RETRO               1006
#define IDC_INS_CONECT                  1007
#define IDC_INS_CONECT_RETRO            1008
#define IDC_DLLDIAGRAMA                 1010
#define IDB_CPOSETIQDIAG                1012
#define IDC_CPOSETIQDIAG                1012
#define IDC_EDIT_IMPLEMENTACION         1012
#define IDB_CANCELAR_EDIC               1013
#define IDC_INS_BLQFUNC_DLL             1013
#define IDC_EDIT_CABECERAS              1013
#define IDB_MOVGRUPOSEL                 1014
#define IDC_MOVGRUPOSEL                 1014
#define IDC_SALVAR_H                    1014
#define IDC_CANCELAR_EDIC               1015
#define IDC_SALVAR_CPP                  1015
#define IDC_DIR_LIBRERIAS               1016
#define IDC_GROSOR                      1017
#define IDC_CLASE_BLOQUE                1017
#define IDC_INCX                        1018
#define IDC_LISTAR_CLASES               1018
#define IDC_INCY                        1019
#define IDC_CLASE_COM                   1019
#define IDC_FORZCOOR                    1020
#define IDC_INSPECCION_CODIGO           1020
#define IDC_VERREJILLA                  1021
#define IDC_GENERACION_CODIGO           1021
#define IDC_ALTURAFLECHA                1022
#define IDC_BLOQUE_DIAGRAMA             1023
#define IDC_POSHORIZONTAL               1024
#define IDC_DIAG_ARBOL                  1025
#define IDC_BLOQUE_ARBOL                1027
#define IDC_PROP_DLL_ARBOL              1028
#define ID_EDIT_CLONE                   2006
#define ID_OBJECT_RESETSIZE             2009
#define IDC_PROHIBIDO                   30982
#define IDC_MOVER                       30988
#define IDC_BLQFUNC                     31000
#define IDC_BLQRETRO                    31001
#define IDC_AREAZOOM                    31002
#define IDC_EDICTXT                     31003
#define IDC_INSCONEC                    31004
#define IDC_INSCONECRETRO               31005
#define IDC_ASOCINI                     31006
#define IDC_ASOCFIN                     31007
#define IDC_MOVGRUPO_PORIG              31008
#define IDC_MOVGRUPO_PDEST              31009
#define IDC_RECTSELEC                   31010
#define IDC_RECTDESELEC                 31011
#define ID_INICIALIZAR_DIAGRAMA         32769
#define ID_PROP_INFORM                  32771
#define ID_AJUSTAR_VENTANA              32772
#define ID_PROP_LISTACONECT             32772
#define ID_ZOOM_TODO                    32773
#define ID_EJECUTAR_DIAG                32773
#define ID_ZOOM_RESTAURAR               32774
#define ID_SELEC_BLOQUE                 32774
#define ID_ZOOM_ACERCAR                 32775
#define ID_SELEC_NUDO                   32775
#define ID_ZOOM_ALEJAR                  32776
#define ID_SELEC_CONECTOR               32776
#define ID_VER_TODO                     32777
#define ID_CONSOLA_MOSTRAR_USUARIO      32778
#define ID_SELECC_ELIMINAR              32778
#define ID_EDIT_OLE_CUT                 32779
#define ID_CONSOLA_MOSTRAR_SISTEMA      32780
#define ID_EDIT_OLE_COPY                32781
#define ID_EDIT_OLE_PASTE               32782
#define ID_SCROLL_AUTO                  32783
#define ID_CONSOLA_MOSTRAR              32784
#define ID_CONSOLA_LIMPIAR              32785
#define ID_ANALIZAR_DLL                 32786
#define ID_CONSOLA_SALVA                32786
#define ID_GENERACION_CODIGO            32787
#define ID_CONSOLA_SALVAR_CON_DIAGRAMA  32788
#define ID_CONSOLA_SALIDA               32788
#define ID_CONSOLA_CORTAR               32789
#define ID_CONSOLA_COPIAR               32790
#define ID_ELIMINAR_BLOQUE              32790
#define ID_PROP_DIAG                    32791
#define ID_CLASEDLL_GENERAR_CODIGO      32792
#define ID_GENERAR_LDD                  32793
#define ID_MENU_COMPONENTE_PROP         32793
#define ID_CLASES_USADAS_SIN_DLL        32794
#define ID_OBJECT_DISPLAYCONTENT        32795
#define ID_OBJECT_DISPLAYASICON         32796
#define ID_OPERAC_ZOOM                  32797
#define ID_EDITAR_DIAG                  32798
#define ID_ENLAZAR_SUBDIAGRAMA          32799
#define ID_CARGAR_SUBDIAGRAMA           32800
#define ID_CANCEL_EDIT                  40001
#define ID_PROP_GEN                     40002
#define ID_PROP_ESPEC                   40003
#define ID_PROP_DLL                     40004
#define ID_OPERACIONES                  40005
#define ID_GENERAR_METAFILE             40008
#define ID_EDIT_COPIARDIAG              40010
#define ID_OLEITEM_BLOQUEAR             40011
#define ID_INICIAR_CONECT               40013
#define ID_NOMBRE_ITEM                  40017
#define ID_CPOSETIQDIAG                 40019
#define ID_INS_BLQFUNC_DIAG             40024
#define ID_INS_BLQFUNC_DLL              40026
#define ID_INS_CONECT                   40029
#define ID_INS_CONECT_RETRO             40030
#define ID_PROPIEDADES                  40031
#define ID_ANYADIRNUDO                  40032
#define ID_ELIMINARNUDO                 40033
#define ID_ELIMINAR_CONEC               40034
#define ID_ANYADIRNUDOPOST              40035
#define ID_ANYADIRNUDOANT               40036
#define ID_ASOCIAR_BLQINI               40037
#define ID_ASOCIAR_BLQFIN               40038
#define ID_CAMBIAPOSETIQ                40039
#define ID_CANCELAR_EDIC                40040
#define ID_INS_BLQ_RETRO                40041
#define ID_VER_TABLADIAG                40043
#define ID_IRALNUDOSIG                  40044
#define ID_IRALNUDOPREV                 40045
#define ID_LIBERAR_RATON                40046
#define ID_GRAVASOCIAR_BLQINI           40047
#define ID_GRAVASOCIAR_BLQFIN           40048
#define ID_PROP_REJILLA                 40049
#define ID_MOVERGRUPO                   40050
#define ID_GENERAR_LDDORIGEN            40051
#define ID_ANULARSELECC                 40052
#define ID_SELECC_TODO                  40054
#define ID_SELECC_RECT                  40055
#define ID_DESELECC_RECT                40056
#define IDP_FAILED_TO_CREATE            65512
#define IDP_OLE_INIT_FAILED             65513

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
